import { FeedBack } from "@/widgets/feedback";
import { Footer } from "@/widgets/footer";
import { SideNavigationBar } from "@/widgets/side-navigation/ui";
import type { Metadata } from "next";
import { ThemeProvider } from "./providers";
import "./styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="bg-white text-black dark:bg-zinc-900 dark:text-white">
        <ThemeProvider>
          <div className="flex w-full min-h-screen">
            <SideNavigationBar />
            <div className="w-11/12 min-h-screen flex flex-col items-center mx-auto px-72">
              {children}
              <Footer />
            </div>
            <FeedBack />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
