import { NextThemeProvider, TanstackQueryProvider } from "@/app/providers";
import "@/app/styles/index.css";
import { FeedBack } from "@/widgets/feedback";
import { Footer } from "@/widgets/footer";
import { SideNavigationBar } from "@/widgets/side-navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// * 프로젝트의 전체 레이아웃 구현체
export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="bg-white text-black dark:bg-zinc-900 dark:text-white">
        <TanstackQueryProvider>
          <NextThemeProvider>
            <div className="flex w-full min-h-screen">
              <SideNavigationBar />
              <div className="min-w-2/3 min-h-screen flex flex-col items-center mx-auto px-72">
                {children}
                <Footer />
              </div>
              <FeedBack />
            </div>
          </NextThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
